### ISSUE TITLE
Metrics are not returning all the statuscake tests

### ISSUE THREAD

**Issue by r1nzl3r-bl4ck** [psychopenguin/prometheus-statuscake-exporter#1]
Hi, 

I have setup up your exporter for statuscake in prometheus but I have seen an issue with statuscake_uptime and statuscake_status metrics, since they only return the first test in my status cake account, I have several tests in SC but they are not shown for those metrics, the statuscake_performance metrics are working well.

**Comment by psychopenguin** [comment]
hi @r1nzl3r-bl4ck thanks for report this. unfortunatelly I'm not using status cake for monitoring, so this exporter is quite unmantained. If you still want to use it, feel free to submit a PR with the changes and I'll merge it. :)
